const ERROR_TYPES = {
  AUTH_ERROR: "AUTH_ERROR",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  SERVER_ERROR: "SERVER_ERROR",
};

module.exports = ERROR_TYPES;